obj-$(CONFIG_RTD128X) += platform.o
obj-$(CONFIG_RTD128X) += irq.o
obj-$(CONFIG_RTD128X) += memory.o
obj-$(CONFIG_RTD128X) += prom.o
obj-$(CONFIG_RTD128X) += setup.o
obj-$(CONFIG_RTD128X) += time.o
obj-$(CONFIG_RTD128X) += board.o
obj-$(CONFIG_RTD128X) += printk.o
obj-$(CONFIG_RTD128X) += sb2.o

