#!/bin/sh
# Print additional version information for non-release trees.

usage() {
	echo "Usage: $0 [srctree]" >&2
	exit 1
}

if grep "CONFIG_MIPS_MT_SMTC=y" .config >/dev/null ; then 
  echo -n "-smtc"
elif grep "CONFIG_MIPS_MT_SMP=y" .config >/dev/null ; then 
  echo -n "-smp"
elif grep "CONFIG_MIPS_VPE_LOADER=y" .config >/dev/null; then 
  echo -n "-vpe"
else
  echo -n "-uni"
fi

cd "${1:-.}" || usage

# Check for git and a git repo.
if head=`git rev-parse --verify HEAD 2>/dev/null`; then
	# Do we have an untagged version?
	if git name-rev --tags HEAD | grep -E '^HEAD[[:space:]]+(.*~[0-9]*|undefined)$' > /dev/null; then
		printf '%s%s' -g `echo "$head" | cut -c1-8`
	fi

	# Are there uncommitted changes?
	if git diff-index HEAD | read dummy; then
		printf '%s' -dirty
	fi
fi
